version: '3.8'
services:
  localstack: 
    image: localstack/localstack:latest
    network_mode: bridge
    ports:
      - "4566:4566" # Edge router
    environment: 
      - SERVICES=s3,lambda,logs
      - DEBUG=1
      - LAMBDA_EXECUTOR=docker-reuse
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock